import { beforeAll, describe, expect, it } from 'vitest';
import { exportMachineAdaptedStreamV2 } from '../formatAdaptation/binaryExportFacade.js';
import { createInvalidBinaryRequestFixture } from '../fixtures/invalidBinaryRequestFixture.js';
import { createUnifiedDSBExplicitFixture } from '../fixtures/unifiedDSBExplicitFixture.js';
import { createUnifiedDSBStrictFixture } from '../fixtures/unifiedDSBStrictFixture.js';
import { createUnifiedDSTExportFixture } from '../fixtures/unifiedDSTExportFixture.js';
import { createUnsupportedBinaryFormatFixture } from '../fixtures/unsupportedBinaryFormatFixture.js';

const equalBytes = (left, right) => left.length === right.length && left.every((value, index) => value === right[index]);

describe('Phase 12D disconnected unified binary export facade', () => {
  let dst; let dsbStrict; let dsbExplicit; let unsupported; let missing;
  const fixtureByName = name => ({ dst, dsbStrict, dsbExplicit, unsupported, missing })[name];
  beforeAll(() => { dst = createUnifiedDSTExportFixture(); dsbStrict = createUnifiedDSBStrictFixture(); dsbExplicit = createUnifiedDSBExplicitFixture(); unsupported = createUnsupportedBinaryFormatFixture(); missing = createInvalidBinaryRequestFixture(); }, 60000);
  it('accepts DST facade export', () => expect(dst.unifiedResult.valid).toBe(true));
  it('selects DST adapter', () => expect(dst.unifiedResult.selectedAdapter).toBe('engineV2-dst'));
  it('creates DST artifact', () => expect(dst.unifiedResult.artifact).not.toBeNull());
  it('preserves DST byte length', () => expect(dst.unifiedResult.artifact.byteLength).toBe(5292));
  it('preserves DST checksum', () => expect(dst.unifiedResult.artifact.checksum).toBe(174));
  it('preserves DST direct bytes', () => expect(equalBytes(dst.unifiedResult.artifact.bytes, dst.directResult.binary.bytes)).toBe(true));
  it('invokes DST exactly once', () => expect(dst.unifiedResult.summary.DSTAdapterInvocationCount).toBe(1));
  it('does not invoke DSB for DST', () => expect(dst.unifiedResult.summary.DSBAdapterInvocationCount).toBe(0));
  it('preserves DST parser result', () => expect(dst.unifiedResult.summary.parserRoundtripPassed).toBe(dst.directResult.summary.parserRoundtripPassed));
  it('preserves DST EOF result', () => expect(dst.unifiedResult.summary.finalEOFPresent).toBe(dst.directResult.summary.finalEOFPresent));
  it('preserves DST source coverage', () => expect(dst.unifiedResult.summary.sourceCommandDispositionCoveragePercent).toBe(dst.directResult.summary.sourceCommandDispositionCoveragePercent));
  it('preserves DST binary lineage', () => expect(dst.unifiedResult.summary.binaryLineageCoveragePercent).toBe(dst.directResult.summary.binaryLineageCoveragePercent));
  it('blocks strict DSB facade export', () => expect(dsbStrict.unifiedResult.status.category).toBe('policy_blocked'));
  it('returns no strict DSB artifact', () => expect(dsbStrict.unifiedResult.artifact).toBeNull());
  it('selects DSB adapter for strict request', () => expect(dsbStrict.unifiedResult.selectedAdapter).toBe('engineV2-dsb'));
  it('invokes strict DSB exactly once', () => expect(dsbStrict.unifiedResult.summary.DSBAdapterInvocationCount).toBe(1));
  it('does not invoke DST for strict DSB', () => expect(dsbStrict.unifiedResult.summary.DSTAdapterInvocationCount).toBe(0));
  it('preserves strict DSB blocked trim count', () => expect(dsbStrict.unifiedResult.formatResult.summary.blockedTrimCount).toBe(17));
  it('preserves strict DSB direct errors', () => expect(dsbStrict.unifiedResult.errors).toEqual(dsbStrict.directResult.errors));
  it('accepts acknowledged explicit DSB', () => expect(dsbExplicit.unifiedResult.valid).toBe(true));
  it('creates explicit DSB artifact', () => expect(dsbExplicit.unifiedResult.artifact).not.toBeNull());
  it('preserves explicit DSB byte length', () => expect(dsbExplicit.unifiedResult.artifact.byteLength).toBe(5139));
  it('preserves explicit DSB checksum', () => expect(dsbExplicit.unifiedResult.artifact.checksum).toBe(45));
  it('preserves explicit DSB direct bytes', () => expect(equalBytes(dsbExplicit.unifiedResult.artifact.bytes, dsbExplicit.directResult.binary.bytes)).toBe(true));
  it('preserves DSB acknowledgement verbatim', () => expect(dsbExplicit.unifiedResult.formatResult.config.trimNoOutputAcknowledgement).toBe(dsbExplicit.formatConfig.trimNoOutputAcknowledgement));
  it('does not claim explicit DSB physical trim encoding', () => expect(dsbExplicit.unifiedResult.summary.physicalTrimEncoded).toBe(false));
  it('does not claim explicit DSB physical trim support', () => expect(dsbExplicit.unifiedResult.summary.physicalTrimSupportVerified).toBe(false));
  it('blocks unsupported format before routing', () => expect(unsupported.unifiedResult.status.category).toBe('unsupported'));
  it('invokes no adapter for unsupported format', () => expect(unsupported.unifiedResult.summary.totalFormatAdapterInvocationCount).toBe(0));
  it('does not claim direct parity for unsupported format', () => expect(unsupported.unifiedResult.summary.formatResultParityPercent).toBe(0));
  it('blocks missing format as invalid request', () => expect(missing.unifiedResult.status.category).toBe('invalid_request'));
  it('uses missing-format reason code', () => expect(missing.unifiedResult.status.reasonCode).toBe('BINARY_EXPORT_FORMAT_REQUIRED'));
  it('invokes no adapter for missing format', () => expect(missing.unifiedResult.summary.totalFormatAdapterInvocationCount).toBe(0));
  it('does not claim direct parity for missing format', () => expect(missing.unifiedResult.summary.formatResultParityPercent).toBe(0));
  it.each([['dst', 'DST'], ['DST', 'DST'], ['dsb', 'DSB'], ['DSB', 'DSB']])('normalizes %s to %s', (format, expected) => { const fixture = expected === 'DST' ? createUnifiedDSTExportFixture(format) : createUnifiedDSBExplicitFixture(format); expect(fixture.unifiedResult.request.format).toBe(expected); });
  it.each(['dst', 'dsbStrict', 'dsbExplicit', 'unsupported', 'missing'])('never uses format fallback for %s', name => expect(fixtureByName(name).unifiedResult.summary.formatFallbackCount).toBe(0));
  it.each(['dst', 'dsbStrict', 'dsbExplicit', 'unsupported', 'missing'])('never invokes cross format for %s', name => expect(fixtureByName(name).unifiedResult.summary.crossFormatInvocationCount).toBe(0));
  it.each(['dst', 'dsbStrict', 'dsbExplicit', 'unsupported', 'missing'])('never invokes Base44 for %s', name => expect(fixtureByName(name).unifiedResult.summary.Base44InvocationCount).toBe(0));
  it.each(['dst', 'dsbStrict', 'dsbExplicit', 'unsupported', 'missing'])('never creates browser download for %s', name => expect(fixtureByName(name).unifiedResult.summary.browserDownloadCreationCount).toBe(0));
  it.each(['dst', 'dsbStrict', 'dsbExplicit', 'unsupported', 'missing'])('never connects application for %s', name => expect(fixtureByName(name).unifiedResult.summary.applicationInvocationCount).toBe(0));
  it.each(['dst', 'dsbStrict', 'dsbExplicit'])('preserves 100 percent format parity for %s', name => expect(fixtureByName(name).unifiedResult.summary.formatResultParityPercent).toBe(100));
  it.each(['dst', 'dsbStrict', 'dsbExplicit'])('does not suppress format warnings for %s', name => expect(fixtureByName(name).unifiedResult.summary.formatWarningSuppressionCount).toBe(0));
  it.each(['dst', 'dsbStrict', 'dsbExplicit'])('does not suppress format errors for %s', name => expect(fixtureByName(name).unifiedResult.summary.formatErrorSuppressionCount).toBe(0));
  it('is deterministic for repeated DST requests', () => { const repeated = exportMachineAdaptedStreamV2({ machineAdaptedStream: dst.machineAdaptedStream, format: 'DST', formatConfig: { label: 'GENERIC_MASCOT' }, metadata: { fixture: 'unified-dst-export' } }); expect(repeated.request.id).toBe(dst.unifiedResult.request.id); expect(repeated.artifact.bytes).toEqual(dst.unifiedResult.artifact.bytes); });
});
