import { beforeAll, describe, expect, it } from 'vitest';
import { adaptMachineCommandStreamToDSB } from '../formatAdaptation/dsbCommandAdapter.js';
import { createDSBBasicFormatFixture, createSyntheticDSBMachineStream } from '../fixtures/dsbBasicFormatFixture.js';
import { createDSBBoundaryMovementFixture } from '../fixtures/dsbBoundaryMovementFixture.js';
import { createDSBColorSequenceFixture } from '../fixtures/dsbColorSequenceFixture.js';
import { createDSBLongJumpFixture } from '../fixtures/dsbLongJumpFixture.js';
import { createDSBTrimPolicyFixture, explicitDSBTrimNoOutputConfig } from '../fixtures/dsbTrimPolicyFixture.js';
import { createDSBZeroMovementFixture } from '../fixtures/dsbZeroMovementFixture.js';
import { createGenericMascotMachineFixture } from '../fixtures/genericMascotMachineFixture.js';

describe('Phase 12C transactional DSB command adapter', () => {
  let generic; let strict; let explicit;
  beforeAll(() => { generic = createGenericMascotMachineFixture(); strict = adaptMachineCommandStreamToDSB(generic.machineAdaptedStream); explicit = adaptMachineCommandStreamToDSB(generic.machineAdaptedStream, explicitDSBTrimNoOutputConfig({ label: 'GENERIC_MASCOT' })); });
  it('blocks generic mascot under strict default', () => expect(strict.valid).toBe(false));
  it('gives all strict source commands dispositions', () => expect(strict.dispositions).toHaveLength(1550));
  it('blocks all seventeen strict trim intents', () => expect(strict.summary.blockedTrimCount).toBe(17));
  it('returns no partial strict record plan', () => expect(strict.recordPlan).toHaveLength(0));
  it('retains strict coverage at 100 percent', () => expect(strict.summary.sourceCommandDispositionCoveragePercent).toBe(100));
  it('accepts generic mascot with acknowledged trim no-output', () => expect(explicit.valid).toBe(true));
  it('gives all explicit source commands dispositions', () => expect(explicit.dispositions).toHaveLength(1550));
  it('maps all seventeen trims to zero output', () => expect(explicit.summary.trimZeroOutputCount).toBe(17));
  it('emits no trim record-plan entries', () => expect(explicit.recordPlan.filter(record => record.source?.type === 'trim')).toHaveLength(0));
  it('preserves acknowledgement verbatim', () => expect(explicit.metadata.trimNoOutputAcknowledgement).toBe(explicit.config.trimNoOutputAcknowledgement));
  it('does not claim physical trim encoding', () => expect(explicit.summary.physicalTrimEncoded).toBe(false));
  it('does not claim physical trim support', () => expect(explicit.summary.physicalTrimSupportVerified).toBe(false));
  it('preserves four color changes', () => expect(explicit.summary.recordPlanColorChangeCount).toBe(4));
  it('preserves one final END', () => expect(explicit.summary.recordPlanEndCount).toBe(1));
  it('keeps every record within 127 units', () => expect(explicit.recordPlan.filter(record => ['stitch', 'jump'].includes(record.type)).every(record => Math.abs(record.dxUnits) <= 127 && Math.abs(record.dyUnits) <= 127)).toBe(true));
  it('verifies exact endpoints', () => expect(explicit.summary.exactFinalEndpointVerified).toBe(true));
  it('does not mutate generic source', () => expect(explicit.summary.sourceStreamMutationCount).toBe(0));
  it.each(['stitch', 'jump'])('maps basic %s movement and END', type => { const result = adaptMachineCommandStreamToDSB(createDSBBasicFormatFixture(type)); expect(result.valid).toBe(true); expect(result.recordPlan.map(record => record.type)).toEqual([type, 'end']); });
  it.each(['stitch', 'jump'])('preserves %s signed deltas', type => { const result = adaptMachineCommandStreamToDSB(createDSBBasicFormatFixture(type)); expect(result.recordPlan[0]).toMatchObject({ dxUnits: 10, dyUnits: -5 }); });
  it.each([-127, 127])('keeps exact stitch boundary %i unsplit', delta => expect(adaptMachineCommandStreamToDSB(createDSBBoundaryMovementFixture('stitch', delta)).recordPlan[0].splitCount).toBe(1));
  it.each([-127, 127])('keeps exact jump boundary %i unsplit', delta => expect(adaptMachineCommandStreamToDSB(createDSBBoundaryMovementFixture('jump', delta)).recordPlan[0].splitCount).toBe(1));
  it.each(['stitch', 'jump'])('splits long %s into three entries', type => expect(adaptMachineCommandStreamToDSB(createDSBLongJumpFixture(350, -280, type)).recordPlan.filter(record => record.type === type)).toHaveLength(3));
  it('encodes zero stitch as an explicit penetration', () => { const result = adaptMachineCommandStreamToDSB(createDSBZeroMovementFixture('stitch')); expect(result.recordPlan[0]).toMatchObject({ type: 'stitch', dxUnits: 0, dyUnits: 0, reasonCode: 'ENCODED_ZERO_DELTA_PENETRATION' }); });
  it('blocks zero stitch when requested', () => expect(adaptMachineCommandStreamToDSB(createDSBZeroMovementFixture('stitch'), { zeroDeltaStitchPolicy: 'block' }).valid).toBe(false));
  it('gives zero jump explicit no-output lineage', () => { const result = adaptMachineCommandStreamToDSB(createDSBZeroMovementFixture('jump')); expect(result.dispositions[0]).toMatchObject({ status: 'zero_output', reasonCode: 'ZERO_DISTANCE_JUMP_NO_BINARY_RECORD' }); });
  it('blocks zero jump when requested', () => expect(adaptMachineCommandStreamToDSB(createDSBZeroMovementFixture('jump'), { zeroDeltaJumpPolicy: 'block' }).valid).toBe(false));
  it('blocks one trim by default', () => expect(adaptMachineCommandStreamToDSB(createDSBTrimPolicyFixture()).summary.blockedTrimCount).toBe(1));
  it('maps one acknowledged trim to zero output', () => expect(adaptMachineCommandStreamToDSB(createDSBTrimPolicyFixture(), explicitDSBTrimNoOutputConfig()).summary.trimZeroOutputCount).toBe(1));
  it('rejects explicit trim policy without acknowledgement', () => expect(adaptMachineCommandStreamToDSB(createDSBTrimPolicyFixture(), { trimPolicy: 'explicit_no_output' }).valid).toBe(false));
  it('rejects acknowledged trim that changes position', () => { const stream = createSyntheticDSBMachineStream([{ type: 'trim', dxUnits: 1, dyUnits: 0 }, { type: 'end' }]); expect(adaptMachineCommandStreamToDSB(stream, explicitDSBTrimNoOutputConfig()).valid).toBe(false); });
  it('preserves color-change thread order', () => { const source = createDSBColorSequenceFixture(4); const result = adaptMachineCommandStreamToDSB(source); expect(result.recordPlan.filter(record => record.type === 'colorChange').map(record => record.source.threadId)).toEqual(source.commands.filter(command => command.type === 'colorChange').map(command => command.threadId)); });
  it('uses contiguous deterministic record indexes', () => expect(explicit.recordPlan.every((record, index) => record.recordPlanIndex === index)).toBe(true));
  it('creates one lineage span per source command', () => expect(explicit.binaryRecordSpans).toHaveLength(1550));
});
