import { beforeAll, describe, expect, it } from 'vitest';
import { buildEngineV2DSBExport } from '../formatAdaptation/dsbExportPipeline.js';
import { createDSBBlockingFixture } from '../fixtures/dsbBlockingFixture.js';
import { createGenericMascotDSBFixture } from '../fixtures/genericMascotDSBFixture.js';
import { explicitDSBTrimNoOutputConfig } from '../fixtures/dsbTrimPolicyFixture.js';

describe('Phase 12C disconnected transactional DSB export pipeline', () => {
  let strict; let explicit;
  beforeAll(() => { strict = createGenericMascotDSBFixture().dsbExport; explicit = createGenericMascotDSBFixture(explicitDSBTrimNoOutputConfig()).dsbExport; });
  it('blocks strict generic mascot transaction', () => expect(strict.valid).toBe(false));
  it('does not create strict generic bytes', () => expect(strict.binary).toBeNull());
  it('reports strict transaction blocked', () => expect(strict.summary.transactionBlocked).toBe(true));
  it('blocks seventeen strict trims', () => expect(strict.summary.blockedTrimCount).toBe(17));
  it('keeps strict source coverage complete', () => expect(strict.summary.sourceCommandDispositionCoveragePercent).toBe(100));
  it('accepts acknowledged explicit generic mascot', () => expect(explicit.valid).toBe(true));
  it('creates explicit generic bytes', () => expect(explicit.binary.byteLength).toBeGreaterThan(512));
  it('maps all 1550 source commands', () => expect(explicit.adaptation.dispositions).toHaveLength(1550));
  it('retains seventeen trims as zero output', () => expect(explicit.summary.trimZeroOutputCount).toBe(17));
  it('emits zero trim binary records', () => expect(explicit.summary.trimBinaryRecordCount).toBe(0));
  it('preserves four color changes', () => expect(explicit.summary.binaryColorChangeRecordCount).toBe(4));
  it('preserves one binary END', () => expect(explicit.summary.binaryEndRecordCount).toBe(1));
  it('appends final EOF', () => expect(explicit.summary.finalEOFPresent).toBe(true));
  it('builds a 512-byte header', () => expect(explicit.summary.headerByteLength).toBe(512));
  it('keeps maximum record delta within 127', () => expect(explicit.summary.maximumRecordDeltaUnits).toBeLessThanOrEqual(127));
  it('verifies exact endpoint', () => expect(explicit.summary.exactFinalEndpointVerified).toBe(true));
  it('has complete binary lineage', () => expect(explicit.summary.binaryLineageCoveragePercent).toBe(100));
  it('has no silent binary lineage drops', () => expect(explicit.summary.silentBinaryLineageDropCount).toBe(0));
  it('passes parser roundtrip', () => expect(explicit.summary.parserRoundtripPassed).toBe(true));
  it('verifies deterministic bytes', () => expect(explicit.summary.deterministicBytesVerified).toBe(true));
  it('does not encode physical trim', () => expect(explicit.summary.physicalTrimEncoded).toBe(false));
  it('does not verify physical trim support', () => expect(explicit.summary.physicalTrimSupportVerified).toBe(false));
  it('does not mutate source', () => expect(explicit.summary.sourceStreamMutationCount).toBe(0));
  it('does not modify encoder source', () => expect(explicit.summary.encoderSourceFileModificationCount).toBe(0));
  it('does not invoke DST', () => expect(explicit.metadata.DSTEncoderInvoked).toBe(false));
  it('does not invoke Base44', () => expect(explicit.metadata.Base44Invoked).toBe(false));
  it('does not connect application', () => expect(explicit.metadata.applicationConnected).toBe(false));
  it('uses low-level DSB encoder functions', () => expect(explicit.metadata.DSBLowLevelEncoderInvoked).toBe(true));
  it('uses stable DSB filename', () => expect(explicit.filename).toBe('GENERIC_MASCOT.dsb'));
  it('uses octet-stream MIME', () => expect(explicit.mimeType).toBe('application/octet-stream'));
  it.each(['invalid_resolution', 'missing_end', 'duplicate_end', 'command_after_end', 'inconsistent_delta', 'initial_color_change', 'trailing_color_change'])('rejects %s without binary output', kind => { const result = buildEngineV2DSBExport({ machineAdaptedStream: createDSBBlockingFixture(kind) }); expect(result.valid).toBe(false); expect(result.binary).toBeNull(); expect(result.metadata.DSBLowLevelEncoderInvoked).toBe(false); });
});
