import { describe, expect, it } from 'vitest';
import { createEmbroideryObjectV2, finalObjectIdForDraft, materializeThreadedEmbroideryObjects, translateDraftDependenciesToFinalObjects, validateEmbroideryObjectV2 } from '../index.js';
import { createBlockedThreadDependencyFixture } from '../fixtures/blockedThreadDependencyFixture.js';
import { createFinalObjectMaterializationFixture } from '../fixtures/finalObjectMaterializationFixture.js';
import { createExactArtworkThreadFixture } from '../fixtures/exactArtworkThreadFixture.js';

const materialize = fixture => materializeThreadedEmbroideryObjects({ regions: fixture.regions, objectDraftMaterialization: fixture.objectDraftMaterialization, threadResolutionConfig: fixture.config });

describe('Phase 6 final object materializer', () => {
  it('keeps retrocompatible holes and visual-color defaults', () => { const object = createEmbroideryObjectV2(); expect(object.holes).toEqual([]); expect(object.visualColor).toBeNull(); });
  it('deeply clones canonical holes and visual color', () => { const input = { holes: [[{ x: 1, y: 1 }, { x: 2, y: 1 }, { x: 1, y: 2 }]], visualColor: { hex: '#ABCDEF' } }; const object = createEmbroideryObjectV2(input); object.holes[0][0].x = 99; object.visualColor.hex = '#000000'; expect(input.holes[0][0].x).toBe(1); expect(input.visualColor.hex).toBe('#ABCDEF'); });
  it('requires a thread ID on canonical final objects', () => expect(validateEmbroideryObjectV2(createEmbroideryObjectV2({ id: 'object:x', regionId: 'r1', role: 'base_fill', stitchType: 'tatami', geometry: [{ x: 0, y: 0 }] })).errors.some(item => item.code === 'MISSING_THREAD_REFERENCE')).toBe(true));
  it('translates final object IDs deterministically', () => expect(finalObjectIdForDraft('draft:proposal:region-a:base_fill')).toBe('object:proposal:region-a:base_fill'));
  it.each([null, '', 'proposal:x'])('rejects invalid draft ID %j', value => expect(finalObjectIdForDraft(value)).toBeNull());
  it('materializes a valid exact-color draft', () => { const result = materialize(createExactArtworkThreadFixture()); expect(result.valid).toBe(true); expect(result.objects).toHaveLength(1); });
  it('assigns every final object a known thread', () => { const result = materialize(createFinalObjectMaterializationFixture()); const ids = new Set(result.threads.map(item => item.id)); expect(result.objects.every(item => ids.has(item.threadId))).toBe(true); });
  it('preserves geometry exactly', () => { const fixture = createFinalObjectMaterializationFixture(); const result = materialize(fixture); result.objects.forEach(object => expect(object.geometry).toEqual(fixture.objectDraftMaterialization.byDraftId[object.source.draftId].geometryMm)); });
  it('preserves holes exactly', () => { const fixture = createFinalObjectMaterializationFixture(); const result = materialize(fixture); result.objects.forEach(object => expect(object.holes).toEqual(fixture.objectDraftMaterialization.byDraftId[object.source.draftId].holesMm)); });
  it('preserves visual color separately from machine color', () => { const fixture = createFinalObjectMaterializationFixture(); const result = materialize(fixture); result.objects.forEach(object => { const draft = fixture.objectDraftMaterialization.byDraftId[object.source.draftId]; expect(object.visualColor).toEqual(draft.visualColor); expect(object.parameters.threadResolution.selectedMachineColor).toBeTruthy(); }); });
  it.each(['role', 'stitchType', 'layer'])('preserves %s', field => { const fixture = createFinalObjectMaterializationFixture(); const result = materialize(fixture); result.objects.forEach(object => expect(object[field]).toEqual(fixture.objectDraftMaterialization.byDraftId[object.source.draftId][field])); });
  it('preserves planning confidence by taking the minimum', () => { const fixture = createExactArtworkThreadFixture(); const result = materialize(fixture); expect(result.objects[0].confidence).toBe(fixture.drafts[0].materializationConfidence); });
  it('adds thread resolution parameters', () => expect(materialize(createExactArtworkThreadFixture()).objects[0].parameters.threadResolution).toMatchObject({ policy: 'artwork_exact', exactMatch: true, physicalSpoolAvailabilityVerified: false }));
  it('marks only thread assignment complete', () => { const deferred = materialize(createExactArtworkThreadFixture()).objects[0].parameters.deferred; expect(deferred.threadAssignment).toBe(false); Object.entries(deferred).filter(([key]) => key !== 'threadAssignment').forEach(([, value]) => expect(value).toBe(true)); });
  it('keeps entry and exit candidates empty', () => { const object = materialize(createExactArtworkThreadFixture()).objects[0]; expect(object.entryCandidates).toEqual([]); expect(object.exitCandidates).toEqual([]); });
  it('preserves source lineage', () => expect(materialize(createExactArtworkThreadFixture()).objects[0].source).toMatchObject({ draftId: 'draft:proposal:exact-artwork', proposalId: 'proposal:exact-artwork', threadResolutionPolicy: 'artwork_exact' }));
  it('translates draft dependencies to final object IDs', () => { const result = materialize(createFinalObjectMaterializationFixture()); const dependent = result.objects.find(item => item.dependencyIds.length); expect(dependent.dependencyIds.every(id => id.startsWith('object:'))).toBe(true); });
  it('propagates blocked dependencies to a fixed point', () => { const result = materialize(createBlockedThreadDependencyFixture()); expect(result.assignments.every(item => item.status === 'blocked')).toBe(true); expect(result.objects).toEqual([]); });
  it('uses the required dependency blocking reason', () => { const result = materialize(createBlockedThreadDependencyFixture()); expect(result.assignments.filter(item => item.reasonCode === 'REQUIRED_THREADED_DEPENDENCY_NOT_MATERIALIZED')).toHaveLength(2); });
  it('can inspect dependency translation independently', () => { const fixture = createBlockedThreadDependencyFixture(); const assignments = fixture.drafts.map(draft => ({ id: `thread-assignment:${draft.id}`, draftId: draft.id, status: draft.visualColor === 'invalid-color' ? 'blocked' : 'assigned', threadId: draft.visualColor === 'invalid-color' ? null : 'thread:x', evidence: [] })); const translated = translateDraftDependenciesToFinalObjects({ drafts: fixture.drafts, assignments, config: fixture.config }); expect(translated.blockedDraftIds).toHaveLength(3); });
  it('builds deterministic execution layers from dependencies only', () => { const fixture = createFinalObjectMaterializationFixture(); const forward = materialize(fixture).executionLayers; fixture.objectDraftMaterialization = { ...fixture.objectDraftMaterialization, drafts: [...fixture.drafts].reverse() }; expect(materialize(fixture).executionLayers).toEqual(forward); });
  it('does not group disconnected objects into thread blocks', () => { const result = materialize(createFinalObjectMaterializationFixture()); expect(Object.hasOwn(result, 'threadBlocks')).toBe(false); expect(result.metadata.threadBlocksCreated).toBe(0); });
  it.each(['commands', 'canonicalCommands'])('does not create %s', field => expect(Object.hasOwn(materialize(createFinalObjectMaterializationFixture()), field)).toBe(false));
  it('does not generate stitch coordinates', () => { const result = materialize(createFinalObjectMaterializationFixture()); expect(result.metadata.stitchCoordinatesGenerated).toBe(false); expect(result.objects.some(item => Object.hasOwn(item, 'stitches'))).toBe(false); });
  it.each(['globalSequencingApplied', 'travelOptimizationApplied', 'machineAdaptationApplied', 'encodingApplied'])('keeps %s false', field => expect(materialize(createFinalObjectMaterializationFixture()).metadata[field]).toBe(false));
  it('does not mutate any input', () => { const fixture = createFinalObjectMaterializationFixture(); const before = structuredClone(fixture); const result = materialize(fixture); expect(fixture).toEqual(before); expect(result.metadata.inputMutationsDetected).toBe(false); });
  it('retains separate objects when they share a thread', () => { const fixture = createFinalObjectMaterializationFixture(); const result = materialize(fixture); const darkObjects = result.objects.filter(item => item.threadId === 'thread:artwork:050505'); expect(darkObjects.length).toBeGreaterThan(1); });
});
