import { describe, expect, it } from 'vitest';
import { buildTechnicalEmbroideryPlan, validateObjectTechnicalSpecificationV2, validateTechnicalEmbroideryPlan } from '../index.js';
import { createGenericMascotTechnicalFixture } from '../fixtures/genericMascotTechnicalFixture.js';

function valid() { const fixture = createGenericMascotTechnicalFixture(); const plan = buildTechnicalEmbroideryPlan({ regions: fixture.regions, threadedObjectMaterialization: fixture.threadedObjectMaterialization }); return { fixture, plan }; }

describe('Phase 7 technical planning validation', () => {
  it('validates a complete plan', () => { const { fixture, plan } = valid(); expect(validateTechnicalEmbroideryPlan(plan, fixture.threadedObjectMaterialization, fixture.regions).valid).toBe(true); });
  it('validates a complete specification', () => { const { fixture, plan } = valid(); expect(validateObjectTechnicalSpecificationV2(plan.specifications[0], { object: fixture.objects.find(item => item.id === plan.specifications[0].objectId), config: plan.config }).valid).toBe(true); });
  it('detects missing specification IDs', () => { const { plan } = valid(); expect(validateObjectTechnicalSpecificationV2({ ...plan.specifications[0], id: null }).errors.some(item => item.code === 'MISSING_TECHNICAL_SPECIFICATION_ID')).toBe(true); });
  it('detects nondeterministic specification IDs', () => { const { plan } = valid(); expect(validateObjectTechnicalSpecificationV2({ ...plan.specifications[0], id: 'technical:random' }).errors.some(item => item.code === 'NONDETERMINISTIC_TECHNICAL_SPECIFICATION_ID')).toBe(true); });
  it('detects duplicate specifications', () => { const { fixture, plan } = valid(); const changed = { ...plan, specifications: [...plan.specifications, plan.specifications[0]] }; expect(validateTechnicalEmbroideryPlan(changed, fixture.threadedObjectMaterialization, fixture.regions).errors.some(item => item.code === 'DUPLICATE_TECHNICAL_SPECIFICATION_ID')).toBe(true); });
  it('detects missing object dispositions', () => { const { fixture, plan } = valid(); const changed = { ...plan, specifications: plan.specifications.slice(1) }; expect(validateTechnicalEmbroideryPlan(changed, fixture.threadedObjectMaterialization, fixture.regions).errors.some(item => item.code === 'FINAL_OBJECT_WITHOUT_TECHNICAL_SPECIFICATION')).toBe(true); });
  it.each([['threadId', 'TECHNICAL_THREAD_ID_MUTATION', 'thread:changed'], ['role', 'TECHNICAL_ROLE_MUTATION', 'highlight'], ['stitchType', 'TECHNICAL_STITCH_TYPE_MUTATION', 'manual']])('detects %s mutation', (field, code, value) => { const { fixture, plan } = valid(); plan.specifications = [{ ...plan.specifications[0], [field]: value }, ...plan.specifications.slice(1)]; expect(validateTechnicalEmbroideryPlan(plan, fixture.threadedObjectMaterialization, fixture.regions).errors.some(item => item.code === code)).toBe(true); });
  it.each([['geometry', 'TECHNICAL_GEOMETRY_MUTATION', [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }]], ['holes', 'TECHNICAL_HOLE_MUTATION', [[{ x: 1, y: 1 }, { x: 2, y: 1 }, { x: 1, y: 2 }]]], ['visualColor', 'TECHNICAL_VISUAL_COLOR_MUTATION', '#000000'], ['layer', 'TECHNICAL_LAYER_MUTATION', 99], ['dependencyIds', 'TECHNICAL_DEPENDENCY_MUTATION', ['object:changed']]])('detects source object %s mutation', (field, code, value) => { const { fixture, plan } = valid(); fixture.threadedObjectMaterialization.objects = fixture.objects.map((item, index) => index ? item : { ...item, [field]: value }); expect(validateTechnicalEmbroideryPlan(plan, fixture.threadedObjectMaterialization, fixture.regions).errors.some(item => item.code === code)).toBe(true); });
  it('detects invalid normalized fill angle', () => { const { plan } = valid(); const spec = { ...plan.specifications[0], fillAnglePlan: { ...plan.specifications[0].fillAnglePlan, normalizedAngleDegrees: 180 } }; expect(validateObjectTechnicalSpecificationV2(spec).errors.some(item => item.code === 'FILL_ANGLE_OUT_OF_RANGE')).toBe(true); });
  it('detects underlay coordinates', () => { const { plan } = valid(); const spec = { ...plan.specifications[0], underlayPlan: { ...plan.specifications[0].underlayPlan, sequence: [{ type: 'edge_run', underlayCoordinates: [] }] } }; expect(validateObjectTechnicalSpecificationV2(spec).errors.some(item => item.code === 'FORBIDDEN_TECHNICAL_FIELD')).toBe(true); });
  it('detects compensation above maximum', () => { const { plan } = valid(); const spec = { ...plan.specifications[0], pullCompensationPlan: { ...plan.specifications[0].pullCompensationPlan, amountMm: 1 } }; expect(validateObjectTechnicalSpecificationV2(spec).errors.some(item => item.code === 'INVALID_PULL_COMPENSATION_PLAN')).toBe(true); });
  it('detects a ready generator with missing requirements', () => { const { plan } = valid(); const spec = { ...plan.specifications[0], generatorReadiness: { ...plan.specifications[0].generatorReadiness, ready: true, missingRequirements: ['X'] } }; expect(validateObjectTechnicalSpecificationV2(spec).errors.some(item => item.code === 'GENERATOR_READY_WITH_MISSING_REQUIREMENTS')).toBe(true); });
  it.each(['threadBlocks', 'commands', 'canonicalCommands', 'machineProfile', 'travelRoute', 'encoder'])('detects forbidden plan field %s', field => { const { fixture, plan } = valid(); const changed = { ...plan, [field]: [] }; expect(validateTechnicalEmbroideryPlan(changed, fixture.threadedObjectMaterialization, fixture.regions).errors.some(item => item.code === 'FORBIDDEN_TECHNICAL_FIELD')).toBe(true); });
});
